apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.4.4
    chart: grafana
    helm:
      parameters:
        - name: 'ingress.hosts[0]'
          value: grafana.ediri.online
        - name: ingress.enabled
          value: 'true'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

