apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-server-domain
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ediri/hello-server
    #argocd-image-updater.argoproj.io/image-list: hello=ediri/hello-server
    #argocd-image-updater.argoproj.io/hello.helm.image-name: hello.image.name
    #argocd-image-updater.argoproj.io/hello.helm.image-tag: hello.image.tag
spec:
  destination:
    namespace: hello-argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: delivery/charts/hello-server
    repoURL: https://github.com/dirien/helloserver.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
